### PR TITLE
Feature/search form

### PR DESCRIPTION
**Pull request by Olena-Horobets**
created markup and styles for search form

### CODE REVIEW

**Review by Iryna-Grabovska — CHANGES_REQUESTED** [review]
Good job!

**Review by vladibon — APPROVED** [review]
Лена умничка!

**Comment by Olena-Horobets** [comment]
> Good job!

thanks a lot. You actually requested changes from me, I can provide them if you specify what should I change)))

**Comment by vladibon** [comment]
Не питай чого в мене заплакані очі... 😩

**Comment by Iryna-Grabovska** [comment]
Don’t worry, be happy ))) Sent from Mail for Windows 10 From: Vladimir BondarSent: Wednesday, October 6, 2021 8:44 PMTo: vladibon/js-team-projectCc: Iryna-Grabovska; Review requestedSubject: Re: [vladibon/js-team-project] Feature/search form (#1) Не питай чого в мене заплакані очі... 😩—You are receiving this because your review was requested.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request merged**
